### ISSUE TITLE
MISO ARX with multiple iddata

### ISSUE THREAD

**Issue by bertrandkerres** [baggepinnen/ControlSystemIdentification.jl#161]
Hello again :),

I was trying to estimate MISO `arx` models from multiple `iddata` instances, and I'm encountering a problem with the broadcasting.

MWE (some parts proudly stolen from your docs):

```julia
using ControlSystemsBase
using ControlSystemIdentification

N  = 2000     # Number of time steps
t  = 1:N
Δt = 1        # Sample time
u  = randn(2, N) # A random control input

G  = ssrand(1, size(u, 1), size(u, 1); Ts=Δt)
y  = lsim(G, u, t)[1][:]
d  = iddata(y, u, Δt)

na = 1
nb = [1, 1]

GIs = arx([d, d], na, nb)          # will also broadcast internally over nb it seems
Gls = arx([d, d], na, Ref(nb)) # will complain about the inputdelay default
```

I could fix my specific example by iterating instead of broadcasting over `getARXregressor` (within `arx`), but I'm not so familiar with the API conventions so I don't know whether that is acceptable as solution in general.

**Comment by baggepinnen** [comment]
This should be fixed by
- https://github.com/baggepinnen/ControlSystemIdentification.jl/pull/162

Note the arguments passed to `arx` in the test to make the two models equivalent. Your random statespace model `G` has `inputdelay = 0` since it has a non-zero $D$ matrix. It also has `na = 2` since it is of order 2, and `nb = 3` since it may have 2 zeros = 3 parameters in the numerator polynomial.

**Comment by bertrandkerres** [comment]
Ah, right, thanks for the help :nerd_face: :+1:
